name: tf-apply.yml
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

concurrency:
  group: terraform-mon-tf
  cancel-in-progress: false

permissions:
  id-token: write
jobs:
  plan_and_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: us-west-2
          role-session-name: terraform-mon
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - run: terraform init
      - id: plan
        run: terraform plan
        if: github.event_name == 'pull_request'
      - id: apply
        if: github.event_name != 'pull_request'
        run: terraform apply -auto-approve
      - name: Store EC2 IP in S3
        if: github.event_name != 'pull_request'
        run: |
          EC2_IP=$(terraform output -raw ec2-ip)
          echo $EC2_IP > ec2-ip.txt
          aws s3 cp ec2-ip.txt s3://terraformmon/ec2-ip.txt
