name: tf-destroy.yml
on:
  workflow_dispatch

concurrency:
  group: terraform-mon-tf
  cancel-in-progress: false
jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: us-west-2
          role-session-name: terraform-mon
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - run: terraform destroy -auto-approve
